### ISSUE TITLE
firestore data only fetched on first visit

### ISSUE THREAD

**Issue by berendsmatt** [mesqueeb/vuex-easy-firestore#242] opened 2019-08-30 00:33 UTC
Hi mate,
I use the code below which works fine opening first collection. However when I next try open a new collection (different or same booking ID) I get no results (I get an observer object rather then the results in console). Strange as I am sure this was working a month ago when I was last working on the code.
```
  async mounted () {
    try {
      await this.$store.dispatch('registrations/openDBChannel', { bookingId: this.$store.state.route.params.bookingId })
    } catch (e) {
      console.error(e)
    }
  },
  async beforeDestroy () {
    await this.$store.dispatch('registrations/closeDBChannel', { clearModule: true })
    console.log('destroyed')
  }
```

**Comment by berendsmatt** [comment] 2019-08-30 00:54
I see {bookingId} param does not work for calls after the first.
`openDBChannel for Firestore PATH: registrations/Pp5FDA60Y1k9elqQITP2/participants/ [registrations/{bookingId}/participants/]`
First call
`openDBChannel for Firestore PATH: registrations/{bookingId}/participants/ [registrations/{bookingId}/participants/]`
Following calls

**Comment by mesqueeb** [comment] 2019-10-14 00:24
Might be related to #253 
Both of these issue's I'm not able to reproduce.

**Comment by berendsmatt** [comment] 2019-10-25 03:40
Legend, much appreciated.

**Comment by berendsmatt** [comment] 2019-10-25 03:41
Woops, wrong button.

**Comment by mesqueeb** [comment] 2019-10-27 23:24
@berendsmatt 
I was able to fix the issue by adding just `commit('myModule/SET_PATHVARS', {myVar})` at first.

However, the other day even with this additional commit before openDBChannel, it still bugged out for me.

I looked into it a little bit more, but it seems that it might have something to do with wether or not Vuex getters are "recalculated" depending on the underlying data.
The bug is present because even though the getter my library uses has its data changed, the getters doesn't always get recalculated... The weird thing is that it's inconsistent, and I'm not sure yet why this is happening.

However, by "console.log"ing the getter it gets recalculated without fail. 😅 
My current work around is as follows:

```js
function openDBChannelsOfCompany (companyId) {
  let path
  const modules = ['myModule1', 'myModule2', 'myModule3'] // etc.
  const promises = productModules.map(moduleName => {
    commit(`${moduleName}/SET_PATHVARS`, {companyId}, {root: true})
    // see: https://github.com/mesqueeb/vuex-easy-firestore/issues/242
    path = rootGetters[`${moduleName}/firestorePathComplete`]
    console.log(path)
    return dispatch(`${moduleName}/openDBChannel`, {companyId}, {root: true})
  })
  Promise.all(promises).then(resolve).catch(reject)
}
```

**Comment by berendsmatt** [comment] 2019-10-28 06:02
Changed my code from the top of post too...
``` 
async mounted () {
    try {
      this.$store.commit('registrations/SET_PATHVARS', { bookingId: this.$store.state.route.params.bookingId }, { root: true })
      console.log(this.$store.state.registrations._sync.pathVariables)
      await this.$store.dispatch('registrations/openDBChannel', { bookingId: this.$store.state.route.params.bookingId })
    } catch (e) {
      console.error(e)
    }
  },
```
...and it seems to be working fine

**Comment by mesqueeb** [comment] 2019-10-28 07:29
@berendsmatt great. I would if I was you, just to be sure console.log that getter that I mentioned instead of the path variable like you do. 
The reason is that I believe it's this getter that is the root of the issue xD

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment] 2019-10-30 07:27
Good news! I think I was able to fix the bug (with some help ♥) and I just pushed the latest version with the fix: `v1.34.4`

Can you install the latest version; delete any work-arounds you had; and try to see if the problem was fixed?

It should be fixed but maybe some apps still have edge-cases, so let me know how it goes 🙃

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>. ☕️<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>

**Closed by mesqueeb** 2019-10-30 07:27 UTC

**Comment by berendsmatt** [comment] 2019-11-01 04:03
Working great

**Comment by mesqueeb** [comment] 2019-11-25 06:17
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
