### ISSUE TITLE
[Bug] modules with overlapping names batch improperly

### ISSUE THREAD

**Issue by BenAHammond** [mesqueeb/vuex-easy-firestore#50] opened 2018-10-05 20:56 UTC
```
      const groupId = 'fooBarBaz';
      await this.$store.dispatch("groups/insert", {
        id: groupId,
      });
      await this.$store.dispatch("usergroups/insert", {
        id: 'tootyFruity',
        groupId,
        userId: this.$store.state.profile.uid,
      });
```

Running both of those insert statements back to back causes two objects to be inserted into the `groups` collection rather than one in both:

```
[vuex-easy-firestore] api call batch:
index.esm.js?34ed:414 Firestore PATH: groups
index.esm.js?34ed:416 updates:  []
index.esm.js?34ed:416 prop deletions:  []
index.esm.js?34ed:416 deletions:  []
index.esm.js?34ed:416 inserts:  (2) [{…}, {…}]
```

Am I doing something wrong or is this a bug?

**Comment by mesqueeb** [comment] 2018-10-06 01:38
@BenAHammond Your code should be alright. Let me quickly try and reproduce this to see if it's a bug or not. Thanks for the report!

**Comment by mesqueeb** [comment] 2018-10-06 03:19
@BenAHammond was able to reproduce. Diving in to fix now.

**Comment by BenAHammond** [comment] 2018-10-08 18:49
Let me know if I can help or help test.

**Comment by mesqueeb** [comment] 2018-10-09 06:59
@BenAHammond Sorry, I was busy with moving this weekend : D
I just [made the Firebase class injectable](https://github.com/mesqueeb/vuex-easy-firestore/blob/master/src/index.ts#L15) so I have better means to use a Mock for testing purposes.

Next step is to test why it groups batches of different modules, but that should be too hard, and the library will be more robust once I add tests for especially that purpose.

It might however take me another few days, so in the mean time manually throttle your requests with 1000 ms in between. Once the first batch synced, the second one should be properly using the other module.

**Comment by BenAHammond** [comment] 2018-10-09 11:52
Hey, thanks for the workaround. That should fix me up for a bit.

**Comment by BenAHammond** [comment] 2018-10-11 01:07
Oddly it doesn't seem to work, believe it or not. Even renaming the `usergroups` module to `ugs` didn't seem to work

```
index.esm.js?34ed:413 [vuex-easy-firestore] api call batch:
index.esm.js?34ed:414 Firestore PATH: groups
index.esm.js?34ed:416 updates:  []
index.esm.js?34ed:416 prop deletions:  []
index.esm.js?34ed:416 deletions:  []
index.esm.js?34ed:416 inserts:  [{…}]
index.esm.js?34ed:413 [vuex-easy-firestore] api call batch:
index.esm.js?34ed:414 Firestore PATH: groups
index.esm.js?34ed:416 updates:  []
index.esm.js?34ed:416 prop deletions:  []
index.esm.js?34ed:416 deletions:  []
index.esm.js?34ed:416 inserts:  [{…}]
index.esm.js?34ed:413 [vuex-easy-firestore] api call batch:
index.esm.js?34ed:414 Firestore PATH: ugs
index.esm.js?34ed:416 updates:  []
index.esm.js?34ed:416 prop deletions:  []
index.esm.js?34ed:416 deletions:  []
index.esm.js?34ed:416 inserts:  []
```

**Comment by mesqueeb** [comment] 2018-10-11 01:19
@BenAHammond wow that’s weird. Give me a few more hours. I’m looking into it now. It’s annoying because the Firestore Mock for testing doesn’t work properly, so i'm doing it manually. 

I have yet to find the origin of the error. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed** 2018-10-11 02:32 UTC

**Comment by mesqueeb** [comment] 2018-10-11 02:37
@BenAHammond I fixed the issue.
Please do `npm i vuex-easy-firestore@latest`
→ make sure it's at least version `1.15.2`

### about the issue
It was a problem with the state of each module being the same JavaScript object, because I had imported the default state object just as an object.

I was able to fix it by making the default state a function that returns the default state object instead of just an object. This way each module will have a different state object instead of a shared object.

You can see the change on [these lines](https://github.com/mesqueeb/vuex-easy-firestore/commit/06d0f3c7dfd844ddf02934d487d8db387d8f7007#diff-94a9af37a89728796c86d62b4271ba46).

**Comment by BenAHammond** [comment] 2018-10-11 02:43
Ah, interesting. Good find and thanks for fixing it!

What are you using for State management? I am enjoying Vuex but really like Redux as well.

**Comment by mesqueeb** [comment] 2018-10-11 03:44
@BenAHammond I have only used Vuex for state management.

I used to LOVE Vuex, because it was so easy for multiple components to reference/use the same state props and actions etc. I've been using Vuex for 2+ years now.

However, recently my programming style changed and after doing a lot of complex projects I stumbled into a lot of cases where Vuex is just not doing it for me anymore.... So currently am not liking Vuex at all because of these reasons:

### 1. Type checking is hard

lately I'm writing everything in TypeScript. And because with Vuex you dispatch and commit with passing a `string` for the action name as first param, it's impossible it do type checking on parameters etc. 🙊

### 2. State props of the central store causes issues with async stuff & multiple actions dispatched simultaneously

Using a central state should be the best way, but in some applications I have written before I had several async actions that required to check/use the same state prop, and had difficulties debugging because these unrelated action would change the state at an arbitrary point when a promise resolves, causing another action that also uses that prop to give unexpected results in some cases.

These cases are very hard to debug because you cannot trace the bug synchronously and several actions are called from different components. I know that this is not a Vuex specific problem, and probably bad programming on my part, but I have encountered this so much, I'm not user what insights I am missing to become a better programmer on this part.

Finally I want to say that Vuex tries to "solve" this by leaving a mutation history, but in my opinion it's still very hard. When looking at the commit history I still have difficulties knowing which actions commit which mutations etc. So it's very hard to know what is wrong when you do something in your app that causes ~30 commits to be made and the order is wrong on a few of these commits (because of asynchronousity). Good luck finding out what you have to change... 🙈

### 3. Writing tests for a Vuex store is hard

I feel that a Vuex store is very difficult to write tests for. It's near impossible to write tests for each mutation/action independently because they receive the modules' local state/dispatch/commit props automatically as first param.

What I'm often doing is importing & instantiating the store to my helper file and just write tests that dispatch a certain action and then do a check on the state of the store. → this is a really bothersome way to write tests and I'm still seeing a lot of bugs that come up in edge cases like this issue. 🙉

### Final words

I am not immediately compelled to try out Redux because I know it's similar to Vuex any way and the basic philosophy of this kind of state management is maybe just not my thing anymore...

I am however greatly interested in GraphQL. I'm probably going to try GraphQL as only state management for my next project and link my components directly to the GraphQL endpoint.

The downside is that I'd need a server with the GraphQL protocol, and currently Firestore doesn't have this. If I like working with GraphQL I'm thinking of writing a library that will act just like GraphQL on the server side but link to regular Firestore endpoints behind the hood.

**Comment by BenAHammond** [comment] 2018-10-11 04:07
What an interesting writeup.

I don't personally use TS and I don't care for typing, but I could
definitely see how that would be an issue. Couldn't you just serialize the
type alongside the contents though?

I agree that a monolithic state is very hard to work with, that's actually
why I like your module so much it makes it natural and easy to break
everything out into modules and more modules. I'd definitely recommend the
same approach with vanilla Vuex/Redux.

GraphQL is definitely interesting and could solve this problem for some use
cases but wouldn't be viable for something like `vuex-easy-firestore`'s
internal state as its a built package.

**Comment by mesqueeb** [comment] 2018-10-11 06:36
@BenAHammond I added a 4th reason & also mention JSDocs now at reason 1.

What do you mean by:
> Couldn't you just serialize the type alongside the contents though?

**Comment by BenAHammond** [comment] 2018-10-11 13:06
Rather than send message "foo" you could serialize an object bar? "{type:
'foo', data: \"{ .... }\"}"

**Comment by BenAHammond** [comment] 2018-10-11 13:35
Sorry I cannot really argue with your TS tooling concerns much as I don't use TS, nor do I have any interest. I come from a strongly typed world, fleeing like a refugee on the shores of reason. Companies have offered me a lot of money to go back and it will never happen.

The only thing I like about JS is the flexibility, TS is a backwards step for me :-)

**Comment by mesqueeb** [comment] 2018-10-12 05:36
@BenAHammond Don't worry, I won't stop making this library awesome. I won't give up on Vuex because I believe that **VueJS version 3** (which is being worked on) and **the next Vuex version** are going to be awesome!
