### ISSUE TITLE
is there a way to insert a new document in doc mode?

### ISSUE THREAD

**Issue by artfabrique** [mesqueeb/vuex-easy-firestore#208] opened 2019-05-15 14:17 UTC
I've found out that using `dispatch("myModule/set", doc)` will not create a new doc if a module is in doc mode. How to properly create a new document in doc mode with turned off automatic initial doc insertion?

Doc object
```js
{
   id: "foo",
   bar: true
}
```

Setup:
```js
  firestorePath: "myModule/{myDocId}",
  firestoreRefType: "doc",
  moduleName: "myModule",
  statePropName: "data",
  sync: {
    guard: ["loading"],
    preventInitialDocInsertion: true
  },
  namespaced: true,
  state,
  getters,
  mutations,
  actions
```

**Comment by mesqueeb** [comment] 2019-05-15 14:53
Hi! 
It’s not possible. 🙃

I think in your case it’s much better to use VEF with a 'collection' instead, that was intended to easily add and edit docs via id. 

Working with 'doc' mode and having a single last path variable is something i’ve seen people do, but i don’t think it’s the best approach to use my library.

I originally created doc mode to just edit a single user document like a “userSettings” page or something similar. 🤔

A pathVariable brings with it many many problems you’ll have to work around when that path changes a lot. 

So my advice would be one of the following two:
- rework your app to work with 'collection' mode
- if you really want to insert just use firebase sdk to manually insert a document. It’s really easy and much better to do so with the sdk directly instead of using my library.
```js
Firebase.firestore().doc('myModule/myCustomId').set({})
```

It’s just that one line. 😸

Btw you can always post your repository, i can have a look and see if i can give some other advice. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by artfabrique** [comment] 2019-05-16 16:19
Got it. And what should be a strategy when you have a collection of heavy documents? For example User Profile or Survey (lots of text and some blob data). When you edit one as an owner you regularly work only with a single item. And regularly you have a separate module to represent a single currently edited item. Then you save it or insert it if the user created a new Survey for ex. or if it's a new user - new User Profile.

**Comment by mesqueeb** [comment] 2019-05-17 09:30
How about giving them "fixed" document id's like so:
- `users/{userId}/userData/profile` for the userProfile
- `users/{userId}/surveys/survey1`
- `users/{userId}/surveys/survey2`

I can image that your surveys would have multiple versions, but "survey1" would be the same for each user?

That way you can just create a VEF module for each survey in your app and make it work specifically with that survey.

Otherwise just use a collection for the surveys: `users/{userId}/surveys`
and then you can use [fetchById](https://mesqueeb.github.io/vuex-easy-firestore/query-data.html#fetching-docs) to fetch a specific survey when a page is opened. Maybe like so:

```js
// in your vue component
created () {
  const id = this.$route.params.id
  this.$store.dispatch('myModule/fetchById', id)
}
```
then if the user goes to `surveys/survey1` it will retrieve that record.

**This is muuuuuuch better than using 'doc' mode and a path variable for the document id.** 😉
Because you won't have to switch out the pathVariable of your VEF module (eg. close and openDBChannel with new variable) every time the user goes to another survey.

Let me know if this works for your use case.

**Comment by artfabrique** [comment] 2019-05-17 09:56
@mesqueeb I think i have some misconception in my head :)
So.. for example I have a collection CollA and I have a module in collection mode.
each document has:
```js
DocN: {
    id: "",
    name: ""
    text: ""
}
```
At first, my module will have
```js
data: {}
```
Then I want to get a list of documents, but only names and ids;
```js
// what should i doo here?
```

Then i expect my module will have
```js
data: {
    "Doc1": {
        id: "Doc1"
        name: "Document 1"
    },
    "Doc2": {
        id: "Doc2"
        name: "Document 2"
    },
    "Doc3": {
        id: "Doc3"
        name: "Document 3"
    }
}
```

Then i want to fetch specific doc using same module:
```js
dispatch("myModule/fetchById", "Doc2");
```
Then i expect my module will have
```js
data: {
    "Doc1": {
        id: "Doc1"
        name: "Document 1"
    },
    "Doc2": {
        id: "Doc2"
        name: "Document 2"
        text: "somelongText" // added to modules' data
    },
    "Doc3": {
        id: "Doc3"
        name: "Document 3"
    }
}
```

Then i want to switch to other document and unload current from memory.
```js
// how to "unfetch" :))?
```

**Comment by mesqueeb** [comment] 2019-05-19 05:00
@artfabrique it's difficult to understand what you mean. Do you have discord? Can you please message me on Discord, i'll get to the bottom of this.

my discord id is `Luca Ban [Mesqueeb]#4774`

**Comment by mesqueeb** [comment] 2019-05-24 23:54
@artfabrique I updated the documentation on firestore path variables:
https://mesqueeb.github.io/vuex-easy-firestore/extra-features.html#variables-for-firestorepath-or-filters

I have added a "bad use case example" chapter, which might be related to your case, so be sure to check it out!

**Comment by mesqueeb** [comment] 2019-05-25 00:10
Also to comment on your question last time:
> Then I want to get a list of documents, but only names and ids;
> `// what should i doo here?`

Firestore's NoSQL database doesn't allow to retrieve "partial" documents. It will always receive the "full document" but no matter how big this document is, you are only charged for 1 read anyway.

Be sure to finish this entire video series called **Get to Know Cloud Firestore**. It has 8 videos and completely explains what a NoSQL DB is, and how to work best with Firestore:
https://www.youtube.com/watch?v=v_hR4K4auoQ&list=PLl-K7zZEsYLluG5MCVEzXAQ7ACZBCuZgZ&index=2&t=3s

I'm going to close this issue for now, but feel free to continue the discussion!

**Closed by mesqueeb** 2019-05-25 00:10 UTC

**Comment by artfabrique** [comment] 2019-05-28 10:41
@mesqueeb thank you very much! Now it's clear to me that firestore is efficient for a large collection of small documents. I think I will separate survey data from the survey documents in a separate collection then and will query it on demand.

**Comment by mesqueeb** [comment] 2019-05-28 13:57
No problem! Also don't forget to think that you're being charged for every read though! 
Good luck and let me know if you're stuck! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by artfabrique** [comment] 2019-05-28 17:40
@mesqueeb i've sent you a friend request on discord :) i'm Revenga#9547
