### ISSUE TITLE
Storing Tokens and Passwords as write - only

### ISSUE THREAD

**Issue by pitw** [mesqueeb/vuex-easy-firestore#160] opened 2019-02-12 13:32 UTC
I have some OAuth Tokens and encrypted passwords user can store in Firestore (App Engine webservice uses it for some syncing in a later step).

I'd like to separate this things completly from Vue / Vuex so user just can write or delete - but never directly retrieve the plain tokens / passwords.

This means I have to create a at least a subcollection (f.ex. "Tokens") which I then can set to write-only with firebase rules.

So in vuex-easy-firestore I need some way to update / create (with subcollection) and retrieve (without subcollection).

In docs I just found the Guards / Fillable - but this doesn't seem the right solution here ?

**Comment by mesqueeb** [comment] 2019-02-12 23:05
This question is more related to general architecture of your client application.

I don’t see why you cannot use a regular vuex easy firestore module and just properly set up your security rules in your console.
What are the problems you are facing when doing so?

Guard & fillables have indeed nothing to do with this and are used for entirely different purposes. I’d love to help you put more but I don’t see what the problem is. xD

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pitw** [comment] 2019-02-12 23:46
In case somebody else have a similar problem - with this firestore rules it seems to work.

```
match /Settings/{document}  {
      allow read, update, delete: if resource.data.created_by == request.auth.uid;
      allow write: if request.auth.uid != null;
      
      function sensitiveData() {
            return get(/databases/$(database)/documents/Settings/$(document)).data
        }
      
      match /sensitive/{document=**}  {
      allow write,delete: if request.auth.uid == sensitiveData().created_by;
      allow read: if false;
    }
    }
```

So sensitive tokens will be stored in subcollection "sensitive" where user just can write + delete but never read. 

Is it true that I have to create 2 modules for updating module + submodule?

```
const settingsModule = {
  firestorePath: 'settings',
  firestoreRefType: 'collection',
  moduleName: 'settings',
  statePropName: 'data',
  namespaced: true, 
}

const sensitiveModule = {
  firestorePath: 'settings/{settingsID}/sensitive',
  firestoreRefType: 'doc',
  moduleName: 'sensitive',
  statePropName: 'data'
}

const id= await dispatch('settingsModule /set', {name: 'John',plz: '3434',city: 'Bern'})

dispatch('sensitiveModule /set', {id, password: 'test', refresh_token: '1234'})

```

**Comment by mesqueeb** [comment] 2019-02-13 00:50
You can create as many vuex easy firestore modules as you want. And you can even nest them by setting the `moduleName` to `settings` and the other to `settings/sensitive` or something.

However, your `firestorePath` is incorrect, the top one is a collection and the bottom one appears to also be a collection. `'settings/{settingsID}'` would be a doc, or `'settings/{settingsID}/sensitive/somethingElse'` would be a doc, but with just 3 parts it's a collection.

Firestore paths always go like this: collection/doc/collection/doc/collection/doc/collection/doc etc....

PS: Remember, all Vuex Easy Firestore does is give you an easy way to retrieve data from Firestore, save it in a module, and give you some pre-defined actions to edit that data.

I'm going to close this issue for now since there isn't really a problem and the thing you want to achieve is something you just have to solve by setting up your security rules, so is not really related to this package. However, feel free to keep the discussion going, i'll try to help where you're stuck. 😉

**Closed by mesqueeb** 2019-02-13 00:50 UTC

**Comment by mesqueeb** [comment] 2019-11-25 06:28
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
