### ISSUE TITLE
deleting key

### ISSUE THREAD

**Issue by zabaat** [mesqueeb/vuex-easy-firestore#224] opened 2019-06-30 19:32 UTC
Client 1 does a delete
```store.dispatch('order/delete', `${activeOrderId}.cart.${key}`)```

and Client 2 shows that as an empty key.

screenshots below
(note the 2 keys in the cart in Client 1 and on Firestore, and the 'empty' key on client 2)

**Vuex on client #1**
![image](https://user-images.githubusercontent.com/3325067/60401179-6cf24e80-9b32-11e9-88b7-8f7b0712d3f6.png)

**Firestore record**
![image](https://user-images.githubusercontent.com/3325067/60401230-0f123680-9b33-11e9-9546-473d195e8932.png)

**Vuex on client #2**
![image](https://user-images.githubusercontent.com/3325067/60401194-a88d1880-9b32-11e9-97de-1ec07655592b.png)

**Comment by mesqueeb** [comment] 2019-07-13 10:18
Duplicate of #180 
Will update in that thread ;)

**Closed by mesqueeb** 2019-07-13 10:18 UTC

**Comment by mesqueeb** [comment] 2019-07-13 11:30
@zabaat is the value that you are trying to delete also a [default value](https://mesqueeb.github.io/vuex-easy-firestore/extra-features.html#default-values)?
