### ISSUE TITLE
‼️ important info for 'doc' mode & firebase auth ‼️

### ISSUE THREAD

**Issue by mesqueeb** [mesqueeb/vuex-easy-firestore#172] opened 2019-03-06 03:30 UTC
‼️ There are issues with the automatic initial doc insert when using 'doc' mode!

### Problem 1: offline + no offline persistence

When the app is _offline_ but there is _no offline persistence_ and the app is opened, the user ID is still saved in browser cache, but the data isn't. **This causes the library to insert an initial doc and will overwrite server data when the app comes back online.**

### Problem 2: a new tab + no multiple tab support

When there is offline persistence but _no multiple tab_ support, and _a new tab_ is opened the same thing as above happens.

### Temporary solution

In the temporary solution below I show how to correctly initialise the Firebase firestore & vuex.

You can see below at `initFirebase()`, when that promise is rejected we **must avoid at all costs to call `openDBChannel` or `fetchAndAdd`.** Other wise the problem described above will occur.

In the solution below I completely avoid creating the vuex store when an error occurs:

```js
import * as Firebase from 'firebase/app'
import 'firebase/firestore'

function initFirebase () {
  Firebase.initializeApp({ /* your Firebase config */})
  return new Promise((resolve, reject) => {
    Firebase.firestore().enablePersistence()
      .then(resolve)
      .catch(err => {
        if (err.code === 'failed-precondition') {
          reject(err)
          // Multiple tabs open, persistence can only be
          // enabled in one tab at a a time.
        } else if (err.code === 'unimplemented') {
          reject(err)
          // The current browser does not support all of
          // the features required to enable persistence
        }
      })
  })
}

initFirebase()
  .then(_ => {
    const easyFirestore = VuexEasyFirestore(myModule, { logging: true, FirebaseDependency: Firebase })
    // init Vuex store
  })
  .catch(error => {
    // take user to a page stating an error occurred
    // (might be a connection error, or the app is open in another tab)
  })

```

I plan on thinking how I can improve this annoyance... Ideas welcome.

Related: #107 

---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉

**Comment by wrburgess** [comment] 2019-03-17 17:07
I can confirm I've seen this problem with my userProfile docs being overwritten with default, blank values when refreshing the browser on an app.

**Comment by mesqueeb** [comment] 2019-03-17 22:27
@wrburgess
I've been working on this, trying to find the best solution...
I'm pushing a fix later today.

**Comment by wrburgess** [comment] 2019-03-17 23:19
Thank you, @mesqueeb. As I learn more about the project, I'll see if I can't help with future issues. I very much appreciate the work you've done here. It's saved me a lot of time from building my own firebase framework.

**Comment by mesqueeb** [comment] 2019-03-18 10:02
Hi @wrburgess I just pushed a fix on the latest version. But according to my tests it doesn't "fix" the actual problem.

Look at the new code here:
https://github.com/mesqueeb/vuex-easy-firestore/blob/master/src/module/actions.ts#L147
(forgot to replace one `var` with `const`, because of copy paste from firebase docs lol)

### Fixes what:
What you can see is that the initialDoc insert is now a transaction which can only succeed if the user is online. When the user is offline nothing will be written.

### The remaining problem:
Even if we can prevent the initial doc from being written with the current fix, the problem remains when another error occurs.

The correct way to initiate Firestore is:

```js
firebase.firestore().enablePersistence()
  .then(resolve)
  .catch(err => {
    if (err.code === 'failed-precondition') {
      reject(err)
      // Multiple tabs open, persistence can only be
      // enabled in one tab at a a time.
    } else if (err.code === 'unimplemented') {
      reject(err)
      // The current browser does not support all of
      // the features required to enable persistence
    }
  })
```

However, as explained by a google employee in this thread:
https://github.com/firebase/firebase-js-sdk/issues/1577

> it's possible to check synchronously whether enabling persistence is guaranteed to fail, but that check is insufficient to determine whether enabling persistence will actually succeed.

So whenever some error occurred the docs might NOT be retrieved and some data will still get overwritten...

I for instance was able to force a `(err.code === 'failed-precondition')` in my app even with the latest patch. This caused the 'doc' mode module to stay with the initial values and overwrite the database values when I reset the app... 😕

All of these problems are non-existent on 'collection' mode, because when an error occurs no docs are loaded anyway. 😅

I'm thinking really hard how to solve this problem, but I'm not sure..... Do you have any ideas for me?

**Comment by wrburgess** [comment] 2019-03-18 20:19
I don't have a solution right off the top of my head. I need to block out some time to analyze and understand the cause of the issue. It's not completely clear to me how it's working.

**Comment by fergusmeiklejohn** [comment] 2019-09-25 06:27
How is Firebase dealing with this in their own SDK? This must be a bug we can replicate just using their SDK no?  If so it seems like the proper way to prevent this is with DB update rules which only they can implement.

**Comment by mesqueeb** [comment] 2019-09-25 08:05
@fergusmeiklejohn this is not a bug we can replicate.
they return an error stating that eg. "multiple tabs are open which is not supported".

When you are still allowing a user to use your app even when under the hood Firebase SDK gave that error, you will be in danger to overwriting user data that was never loaded because of the error.

The reason is that you can still dispatch _write_ actions, even though the _data fetching_ had silently failed.

That's why it's the job of the dev to take action and not allow the user to use the app when the Firebase SDK gives that error.

I hope you understand 😉

**Comment by mesqueeb** [comment] 2019-11-25 03:37
---
After about two years of open source, I finally got accepted for Github Sponsors!
💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!
BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
On to many more years of open-sourcing! 🎉

**Comment by louisameline** [comment] 2019-12-05 20:53
As far as I can see, the initial document insertion happens in two places:
- in `openDBChannel`. Here, we can check that the `source` of the first (empty) data received is `server` before inserting the initial doc
- in `fetchAndAdd`. Here, it's done in the promise callback, which is supposed to happen only after server retrieval, so it's not supposed to be an issue

But it seems too simple, I guess I missed something ^^'
BTW, just to disambiguate, when you say "*no multiple tab* support", you mean when the option for multiple tab is disabled, right?

**Comment by louisameline** [comment] 2019-12-07 00:07
I think I understand what the mistake was. The library actually didn't make the difference between local data and remotely-loaded data. Should be fixed with my PR :)

Now the problem is that the initial insertion should not have been made into a transaction, it makes things harder when you're dealing with people with bad connectivity. @mesqueeb I'll let you do your tests and revert the transaction thing if it's ok for you? Thank you

**Closed** 2019-12-10 13:18 UTC
Labels: bug

**Comment by mesqueeb** [comment] 2019-12-10 13:22
@Nrevi Thanks to the incredible PR of @louisameline we were able to solve this issue!
🎉🎉🎉
